import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children , params:{locale} }) {
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} >
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
